[application]
name = "DeadlineTracker"

[bundle]
identifier = "com.yangyiming.deadlinetracker"
publisher = "Yang Yiming"
icon = ["assets/icon.png"]

[web.app]

# HTML title tag content
title = "deadline-tracker"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
